### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by SerejS** [npv3s/AlgLabs#2]
Твой код гавно!!!!

**Comment by npv3s** [comment]
ТВОЙ код гавно!!!!

**Comment by Densi61** [comment]
Привет!!!! А может твой?

чт, 14 нояб. 2019 г., 13:33 Nikolai <notifications@github.com>:

**Comment by npv3s** [comment]
Репозиторий попутал?

**Comment by Densi61** [comment]
Да, и что?

чт, 14 нояб. 2019 г., 13:37 Nikolai <notifications@github.com>:

**Comment by npv3s** [comment]
Иди ругаться в свой!
